# A conda environment for hillslope-channel coupling 
# Based upon the espin environment with autoreload added, so far
# Usage:
#   $ conda env create --file=environment.yaml
#   $ source activate slopesChannels

name: slopesChannels
channels:
  - conda-forge
dependencies:
  - python =3
  - pip
  - numpy
  - scipy
  - pandas
  - notebook
  - rasterio
  - pytest
  - coverage
  - bmipy
  - pymt >=1.1
  - landlab >=2.0
  - terrainbento
  - pymt_child
  - pymt_hydrotrend
  - pymt_sedflux
  - bmi-topography
  - imageio
  - pip:
    - tdqm
    - imageio-ffmpeg
